-- RentEZ — demo data for local development and the presentation.
-- rentez_startup_project_v1_1_20260810_1421SGT
--
-- Run with: make seed
--
-- WHY THIS IS NOT A FLYWAY MIGRATION
-- Migrations are schema and live in version control forever. Seed data is
-- throwaway demo content. Mixing them puts fake customers in the production
-- schema history, and makes it impossible to re-run a load test against a
-- clean database without rebuilding the schema.
--
-- PREFER THE SEED PROFILE OVER THIS FILE.
-- Each service ships a profile-gated DataSeeder bean, and
--
--     SPRING_PROFILES_ACTIVE=seed make up
--
-- is the supported way to get demo accounts and a starter fleet. Those seeders
-- go through the same code path the application uses, so BCrypt hashes are real
-- and enum values cannot drift. This file exists for bulk data that would be
-- slow to insert through the API — the 200 vehicles the load test wants — and
-- is intentionally empty until someone needs exactly that.

SELECT 'RentEZ seed: no data loaded yet — use SPRING_PROFILES_ACTIVE=seed make up' AS status;

-- ============================================ M1 · rentez_auth (account-service)
-- The table is app_user, not `users`. Passwords must be real BCrypt hashes;
-- register once through /api/accounts and copy the stored hash rather than
-- inventing one.
--
-- INSERT INTO rentez_auth.app_user
--   (full_name, email, password_hash, role, enabled, created_at) VALUES
--   ('Demo Admin',    'admin@rentez.test',    '$2a$12$REPLACE_ME', 'ADMIN',    TRUE, NOW()),
--   ('Demo Staff',    'staff@rentez.test',    '$2a$12$REPLACE_ME', 'STAFF',    TRUE, NOW()),
--   ('Demo Customer', 'customer@rentez.test', '$2a$12$REPLACE_ME', 'CUSTOMER', TRUE, NOW())
-- ON CONFLICT (email) DO NOTHING;

-- =========================================== M2 · rentez_fleet (catalog-service)
-- PRD assumption 10: approximately 200 vehicles and 50 seeded customers. Five is
-- enough for development; generate the full 200 here for the load test, which is
-- the one case where going through the API would be needlessly slow.
--
-- The table is car, and the richer fleet model in docs/ch02 (locations,
-- categories, rate_plans) is a later migration that does not exist yet — daily
-- rate lives on the car row for now.
--
-- INSERT INTO rentez_fleet.car
--   (make, model, model_year, daily_rate, location, type, status) VALUES
--   ('Toyota',  'Corolla Altis', 2023,  85.00, 'Raffles Place',  'SEDAN',     'AVAILABLE'),
--   ('Honda',   'Vezel',         2022, 120.00, 'Raffles Place',  'SUV',       'AVAILABLE'),
--   ('Hyundai', 'Avante',        2024,  90.00, 'Changi T3',      'SEDAN',     'AVAILABLE'),
--   ('Toyota',  'Alphard',       2021, 190.00, 'Changi T3',      'LUXURY',    'MAINTENANCE'),
--   ('Tesla',   'Model 3',       2024, 160.00, 'Raffles Place',  'ELECTRIC',  'AVAILABLE');
--
-- Postgres note: ON CONFLICT needs a unique constraint to target, and car has
-- none beyond the primary key. Either add a plate number column first or rely on
-- `make clean` for idempotence, which is what the seed profile does.

-- ====================================== M3 · rentez_booking (reservation-service)
-- Leave empty. Bookings must be created through the API so that the rows in
-- booking_day are written by the same code path the load test exercises — that
-- table's composite primary key IS the concurrency guarantee, and seeding around
-- it would prove nothing.
