name: Deploy Production

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
