-- rentez_payment - PRD module M4, Payment and Refund.
--
-- The schema, the payment_user role and PAYMENT_DB_PASSWORD were provisioned
-- in db/init/01-schemas.sql long before this service existed. Ported from the
-- monolith's `payment` table, with Payment.booking (@ManyToOne) replaced by a
-- plain booking_id - no foreign key leaves this schema.

CREATE TABLE payment (
    id                   BIGINT         GENERATED BY DEFAULT AS IDENTITY,

    -- rentez_booking.booking.id. An identifier, never a reference.
    booking_id           BIGINT         NOT NULL,
    -- Snapshot, so a receipt still identifies its customer without asking
    -- account-service or reservation-service anything.
    customer_id          BIGINT         NOT NULL,
    customer_email       VARCHAR(255)   NOT NULL,

    -- Client-supplied via the Idempotency-Key header, or generated when absent.
    -- A retry of the same request returns the original payment instead of
    -- charging twice. NOT derived from booking_id: a legitimate retry after a
    -- declined attempt has to be allowed to create a new payment.
    idempotency_key      VARCHAR(64)    NOT NULL,

    amount               DECIMAL(12, 2) NOT NULL,
    -- VARCHAR(3), not CHAR(3). Postgres blank-pads CHAR on retrieval where MySQL
    -- strips it, so a ported CHAR column hands back 'SGD' today and 'SG ' the
    -- day someone adds a two-letter code. Matches @Column(length = 3).
    currency             VARCHAR(3)     NOT NULL DEFAULT 'SGD',
    method               VARCHAR(16)    NOT NULL,

    -- INITIATED exists because the row is written BEFORE the gateway is called.
    -- The monolith saved only after the gateway returned, so a crash in between
    -- meant the money moved with nothing recorded anywhere. Ported as-is into a
    -- service that can be killed mid-request, that is a real hole.
    status               VARCHAR(16)    NOT NULL DEFAULT 'INITIATED',

    -- Where the saga got to, tracked separately from the money. A payment can be
    -- SUCCESS while the booking is not yet confirmed - that is precisely the
    -- window the sweeper exists to close.
    confirm_state        VARCHAR(24)    NOT NULL DEFAULT 'PENDING',

    transaction_ref      VARCHAR(64)    NULL,
    failure_reason       VARCHAR(255)   NULL,
    attempt_count        INT            NOT NULL DEFAULT 0,
    last_error           VARCHAR(1000)  NULL,

    created_at           TIMESTAMP(6)   NOT NULL,
    updated_at           TIMESTAMP(6)   NOT NULL,

    PRIMARY KEY (id),
    CONSTRAINT uk_payment_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT uk_payment_transaction_ref UNIQUE (transaction_ref),
    CONSTRAINT ck_payment_status CHECK (status IN ('INITIATED', 'SUCCESS', 'FAILED', 'REFUNDED')),
    CONSTRAINT ck_payment_confirm_state CHECK (confirm_state IN
        ('PENDING', 'CONFIRMED', 'COMPENSATED', 'AWAITING_COMPENSATION', 'NOT_APPLICABLE'))
);

-- The second guarantee, and the one that survives a client that forgets to send
-- an idempotency key: at most one SUCCESS per booking, enforced by the database
-- rather than by application logic that could race with itself. Any number of
-- FAILED attempts remain fine.
--
-- THIS IS WHERE POSTGRES IS SIMPLY BETTER THAN MYSQL, and it is worth a line in
-- the report. MySQL has no partial index, so the same rule needed a STORED
-- generated column that evaluated to NULL for every non-SUCCESS row, relying on
-- NULLs not colliding in a unique index - plus a read-only mirror field on the
-- Payment entity that existed purely so ddl-auto=validate would account for the
-- column. Postgres expresses the intent directly in one line, and both the
-- generated column and the phantom Java field are deleted.
CREATE UNIQUE INDEX uk_payment_success_booking
    ON payment (booking_id) WHERE status = 'SUCCESS';

CREATE INDEX ix_payment_booking ON payment (booking_id);
CREATE INDEX ix_payment_customer_created ON payment (customer_id, created_at DESC);
-- The reconciliation sweeper's query: money taken, saga unfinished.
CREATE INDEX ix_payment_status_confirm_state ON payment (status, confirm_state);

-- Same transactional outbox as reservation. Payment receipts and refund notices
-- are committed with the payment and delivered afterwards, so notification is
-- never on the critical path of taking money.
CREATE TABLE outbox_event (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    event_id      VARCHAR(36)   NOT NULL,
    event_type    VARCHAR(64)   NOT NULL,
    -- JSONB over a String field mapped with @JdbcTypeCode(SqlTypes.JSON) - see
    -- the fuller note in reservation-service's V1__init.sql.
    payload       JSONB         NOT NULL,
    status        VARCHAR(16)   NOT NULL DEFAULT 'PENDING',
    attempt_count INT           NOT NULL DEFAULT 0,
    last_error    VARCHAR(1000) NULL,
    created_at    TIMESTAMP(6)  NOT NULL,
    dispatched_at TIMESTAMP(6)  NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_outbox_event_id UNIQUE (event_id),
    CONSTRAINT ck_outbox_status CHECK (status IN ('PENDING', 'DISPATCHED', 'FAILED'))
);

CREATE INDEX ix_outbox_status_created ON outbox_event (status, created_at);

CREATE TABLE audit_log (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    actor_email VARCHAR(255)  NULL,
    action      VARCHAR(64)   NOT NULL,
    entity_type VARCHAR(64)   NOT NULL,
    entity_id   BIGINT        NULL,
    details     VARCHAR(1000) NULL,
    occurred_at TIMESTAMP(6)  NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX ix_audit_log_occurred_at ON audit_log (occurred_at DESC);
